# @format

name: restaurants_finder
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  velocity_x: 3.5.1
  retrofit: 3.0.2+1
  faker: 2.0.0
  flutter_fadein: 2.0.0
  shimmer: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  retrofit_generator: 4.0.0
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
